### PR TITLE
vet and lint fixes

### PR DESCRIPTION
**Pull request by mvdan**
The "passing locks by value" bit could well be a bugfix, let's hope that's not the case :)

### CODE REVIEW

**Comment by mvdan** [comment]
I messed up the tests a bit, will be amending the commits in a moment.

**Comment by mvdan** [comment]
Commits fixed, it was a silly pointer reference typo.

The tests still fail, but they already fail in master, not due to these changes.

**Comment by mvdan** [comment]
Ping anyone?

**Comment by mtrythall** [comment]
Sorry @mvdan - We missed this. We'll take a look at it early next week.

**Comment by mvdan** [comment]
Reping :)

**Comment by yml** [comment]
@mvdan my bad for not following up here earlier.

I merged your branch outside github [2 weeks ago](https://github.com/BotBotMe/botbot-bot/commits/master) because I did this in a place where I didn't have network.

Thank you very much for your contribution.

**Pull request closed without merging**
